version: '3'
services:
          web:
                    build: .
                    ports:
                              - "80:5000"

          krolik:
                    image: "rabbitmq:alpine"

          mailer:
                    build: mailer
